### ISSUE TITLE
Support for M1/M2 on macOS

### ISSUE THREAD

**Issue by muued** [PrzemyslawSwiderski/python-gradle-plugin#12]
For macOS systems using M1/M2 CPUs, the `os.arch` is 'aarch64' and the corresponding miniconda variant is 'arm64', which should be taken as the value for `arch` here. Currently, it is hardcoded to 'x86_64', which results in a failure during condaSetup.

**Comment by PrzemyslawSwiderski** [comment]
@muued Support should be provided in the latest `2.3.0` plugin version.
For older versions, it should be possible to configure target architecture by setting `systemArch` plugin's parameter to `arm64` like in the `README.md` file.

Thank you for your report.

**Comment by muued** [comment]
Thank you for solving this in no time, works like a charm
