### ISSUE TITLE
Redirect output to Logger, instead of System out, so I can control the logged output with Gradle log-level flags

### ISSUE THREAD

**Issue by adam-enko** [PrzemyslawSwiderski/python-gradle-plugin#22]
Currently the execution output is redirected to System output (unless there is a file present).

https://github.com/PrzemyslawSwiderski/python-gradle-plugin/blob/eba0c9ca6a306f8b3dcf45c5a21f76ed0bf7fceb/src/main/kotlin/com/pswidersk/gradle/python/VenvTask.kt#L121

This means when I run a task in Gradle with the `--quiet` tag, I still view output from the tasks. Often this is quite verbose and not necessary. 

I'd be happy to contribute a PR.

### Suggestion

1. Quick fix: Add a condition to check the current log level before forwarding to stdout.

2. Forward the output stream to the task's Logger.

**Comment by PrzemyslawSwiderski** [comment]
Hi @adam-enko,
I think the 2. option would be the best since as you wrote, we could hide/show output by adding flag to Gradle.

**Comment by PrzemyslawSwiderski** [comment]
Created the PR #23. 
Looks like `logging.captureStandardOutput(LIFECYCLE)` inside of exec was all we needed.
@adam-enko please let me know if this will work for you :slightly_smiling_face:

**Comment by adam-enko** [comment]
Thanks for taking a look! I'll review the PR.

**Comment by PrzemyslawSwiderski** [comment]
Changes should be available in the latest `2.5.0` plugin version.
