### ISSUE TITLE
Improve compatibility with the Gradle configuration cache

### ISSUE THREAD

**Issue by aSemy** [PrzemyslawSwiderski/python-gradle-plugin#4]
Hi, I'm just looking at this project and I set up a simple 'hello, world', but I'm getting some Gradle [configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html) warnings

```none
5 problems were found storing the configuration cache.
- Task `:envSetup` of type `com.pswidersk.gradle.python.EnvSetupTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/7.4.2/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
- Task `:main` of type `com.pswidersk.gradle.python.VenvTask`: cannot serialize object of type 'java.io.ByteArrayInputStream', a subtype of 'java.io.InputStream', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.4.2/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:main` of type `com.pswidersk.gradle.python.VenvTask`: cannot serialize object of type 'org.apache.commons.io.output.CloseShieldOutputStream', a subtype of 'java.io.OutputStream', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.4.2/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:main` of type `com.pswidersk.gradle.python.VenvTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/7.4.2/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
- Task `:minicondaSetup` of type `com.pswidersk.gradle.python.MinicondaSetupTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/7.4.2/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
```

The configuration cache is nice because it *really* improves the speed of Gradle. But mostly I want to get rid of the ugly warnings :)

These are usually pretty simple problems to fix. Usually you just replace any reference to a Gradle Project with an alternative.

There's a table with replacements a bit further down on this page: https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution

**Comment by PrzemyslawSwiderski** [comment]
Thank you @aSemy for reporting this issue. I will try to fix it as soon as possible 😊

**Comment by PrzemyslawSwiderski** [comment]
Hi @aSemy, I created a [MR](https://github.com/PrzemyslawSwiderski/python-gradle-plugin/pull/5) with fixes.
Input/Output related warnings will still appear since those are not supported types in terms of configuration cache.
Currently I've added a `notCompatibleWithConfigurationCache(...)` method in constructor to mitigate this issue but I will try to find some other solution. Do you know if there is a possibility to ignore specific property in tasks instead of a whole task?

**Comment by aSemy** [comment]
@PrzemyslawSwiderski Looks really really great! Good work! I've got some suggested improvements - I'll make a new PR.

I don't know if it's possible to ignore a specific property. But I think most people just turn the errors into warnings.

```properties
# gradle.properties

org.gradle.unsafe.configuration-cache=true
org.gradle.unsafe.configuration-cache-problems=warn
```

So while the logs get spammed, it doesn't really matter.

**Comment by PrzemyslawSwiderski** [comment]
@aSemy Thank you for creating your refactoring PR. I updated my PR with suggestions from it. 
I also replaced `standardInput` and `standardOutput` `VenvTask` fields with optional `inputFile` and `outputFile` so that Gradle configuration cache should not complain any more.
